import { makeGeometry } from './mesh-utils.js';
import { sampleMap } from './image-relief.js';
function isActive(map,u,v){const s=map.silhouette?sampleMap(map,'silhouette',u,v):sampleMap(map,'mask',u,v);return s>.46}
function surfaceZ(map,params,u,v){const lum=sampleMap(map,'luminance',u,v),edge=sampleMap(map,'edge',u,v),detail=sampleMap(map,'detail',u,v),shadow=sampleMap(map,'shadow',u,v),highlight=sampleMap(map,'highlight',u,v),micro=sampleMap(map,'micro',u,v),learned=sampleMap(map,'relief',u,v),ink=Math.pow(Math.max(0,1-lum),1.12),base=Math.max(1.6,params.pendantBase),depth=params.reliefDepth*params.reliefDetail;
if(params.relief==='laser'){const line=Math.min(1,detail*.70+edge*.48+shadow*.22+Math.abs(micro)*.16+ink*.025),eased=line*line*(3-2*line);return Math.max(base-.72,base-Math.min(depth,.72)*eased)}
if(params.relief==='emboss'){const form=Math.max(-.15,Math.min(1,shadow*.68+detail*.32+edge*.08-highlight*.24+learned*.28)),eased=Math.sign(form)*Math.pow(Math.abs(form),.82);return Math.max(base*.82,base+Math.min(depth,2.35)*eased)}
const form=Math.max(-.32,Math.min(1,shadow*.72+ink*.18+detail*.30+edge*.06-highlight*.32+learned*.35+micro*.10)),eased=Math.sign(form)*Math.pow(Math.abs(form),.78);return Math.max(base*.76,base+Math.min(depth,2.7)*eased)}
function cellActive(map,x,y,nx,ny){return x>=0&&y>=0&&x<nx&&y<ny&&isActive(map,(x+.5)/nx,(y+.5)/ny)}
export function buildPendantGeometry(map,params,resolution=170){const aspect=map?.aspect||.78,nx=Math.max(64,resolution),ny=Math.max(64,Math.round(resolution/aspect)),width=params.pendantWidth,height=width/aspect,positions=[],indices=[],top=Array.from({length:ny+1},()=>Array(nx+1).fill(-1)),bottom=Array.from({length:ny+1},()=>Array(nx+1).fill(-1)),active=[];for(let y=0;y<ny;y++){active[y]=[];for(let x=0;x<nx;x++)active[y][x]=cellActive(map,x,y,nx,ny)}function projectedUV(x,y){let u=x/nx,v=y/ny;if(!map.silhouette)return[u,v];const s=sampleMap(map,'silhouette',u,v);if(s>.15&&s<.85){const du=1/Math.max(map.w,nx),dv=1/Math.max(map.h,ny),gx=(sampleMap(map,'silhouette',Math.min(1,u+du),v)-sampleMap(map,'silhouette',Math.max(0,u-du),v))/(2*du),gy=(sampleMap(map,'silhouette',u,Math.min(1,v+dv))-sampleMap(map,'silhouette',u,Math.max(0,v-dv)))/(2*dv),g2=gx*gx+gy*gy;if(g2>1e-8){const shift=(.5-s)/g2;u=Math.max(0,Math.min(1,u+gx*shift));v=Math.max(0,Math.min(1,v+gy*shift))}}return[u,v]}function cornerNeeded(x,y){for(let oy=-1;oy<=0;oy++)for(let ox=-1;ox<=0;ox++){const cx=x+ox,cy=y+oy;if(cx>=0&&cy>=0&&cx<nx&&cy<ny&&active[cy][cx])return true}return false}for(let y=0;y<=ny;y++)for(let x=0;x<=nx;x++){if(!cornerNeeded(x,y))continue;const[u,v]=projectedUV(x,y),X=(u-.5)*width,Y=(.5-v)*height;top[y][x]=positions.length/3;positions.push(X,Y,surfaceZ(map,params,u,v));bottom[y][x]=positions.length/3;positions.push(X,Y,0)}const addFaces=(x,y)=>{const a=top[y][x],b=top[y][x+1],c=top[y+1][x+1],d=top[y+1][x],A=bottom[y][x],B=bottom[y][x+1],C=bottom[y+1][x+1],D=bottom[y+1][x];if([a,b,c,d,A,B,C,D].some(i=>i<0))return;indices.push(a,d,b,b,d,c,A,B,D,B,C,D)},wall=(t1,t2,b1,b2,flip=false)=>{if([t1,t2,b1,b2].some(i=>i<0))return;if(flip)indices.push(t1,t2,b1,t2,b2,b1);else indices.push(t1,b1,t2,t2,b1,b2)};for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){if(!active[y][x])continue;addFaces(x,y);if(x===0||!active[y][x-1])wall(top[y][x],top[y+1][x],bottom[y][x],bottom[y+1][x]);if(x===nx-1||!active[y][x+1])wall(top[y][x+1],top[y+1][x+1],bottom[y][x+1],bottom[y+1][x+1],true);if(y===0||!active[y-1][x])wall(top[y][x],top[y][x+1],bottom[y][x],bottom[y][x+1],true);if(y===ny-1||!active[y+1][x])wall(top[y+1][x],top[y+1][x+1],bottom[y+1][x],bottom[y+1][x+1])}const geometry=makeGeometry(positions,indices);geometry.computeVertexNormals();return geometry}
